const { StoriesDB } = require("../../Adapters/DB/stories_db")
const { buildAddStory } = require("./add_story")
const { buildDeleteStoryById } = require("./delete_story_by_id")
const { buildGetStoryByid } = require("./get_story_by_id")
const { Id } = require("../../CustomHelpers/Id_helper")
const { AppError, AppErrorMessages } = require("../../app_error")
const { buildLikeStory } = require("./like_story")
const { buildUnlikeStory } = require("./unlike_story")
const { UsersDB } = require("../../Adapters/DB/users_db")
const { buildViewStory } = require("./view_story")
const { buildUnviewStory } = require("./unview_story")
const { buildGetLastDayStoriesCount } = require("./get_last_day_stories_count")
const { buildisStoryLiked } = require("./is_story_liked")
const { buildGetLastDayStoriesByPublisherId } = require("./get_last_day_stories")
const { buildGetStoriesArchiveByPublisherId } = require("./get_stories_archive")

const addStory = buildAddStory({ StoriesDB })
const deleteStoryById = buildDeleteStoryById({ StoriesDB, Id, AppError, AppErrorMessages })
const getStoryById = buildGetStoryByid({ StoriesDB, Id, AppError, AppErrorMessages })
const likeStory = buildLikeStory({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })
const unlikeStory = buildUnlikeStory({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })
const viewStory = buildViewStory({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })
const unviewStory = buildUnviewStory({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })
const getLastDayStoriesCount = buildGetLastDayStoriesCount({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })
const getLastDayStoriesByPublisherId = buildGetLastDayStoriesByPublisherId({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })
const getStoriesArchiveByPublisherId = buildGetStoriesArchiveByPublisherId({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })

const isStoryLiked = buildisStoryLiked({ UsersDB, StoriesDB, Id, AppError, AppErrorMessages })

module.exports = { addStory, deleteStoryById, getStoryById, likeStory, unlikeStory, getLastDayStoriesByPublisherId, viewStory, unviewStory, getLastDayStoriesCount, getStoriesArchiveByPublisherId, isStoryLiked }