const { StoriesDB } = require("../../Adapters/DB/stories_db")
const { buildAddStory } = require("./add_story")
const { buildDeleteStoryById } = require("./delete_story_by_id")
const { buildGetStoryByid } = require("./get_story_by_id")
const { Id } = require("../../CustomHelpers/Id_helper")
const { AppError } = require("../../app_error")
const { buildLikeStory } = require("./like_story")
const { buildUnlikeStory } = require("./unlike_story")
const { UsersDB } = require("../../Adapters/DB/users_db")
const { buildGetStoriesByPublisherId } = require("./get_stories_by_publisher_id")
const { buildViewStory } = require("./view_story")
const { buildUnviewStory } = require("./unview_story")

const addStory = buildAddStory({ StoriesDB })
const deleteStoryById = buildDeleteStoryById({ StoriesDB, Id, AppError })
const getStoryById = buildGetStoryByid({ StoriesDB, Id, AppError })
const likeStory = buildLikeStory({ UsersDB, StoriesDB, Id, AppError })
const unlikeStory = buildUnlikeStory({ UsersDB, StoriesDB, Id, AppError })
const viewStory = buildViewStory({ UsersDB, StoriesDB, Id, AppError })
const unviewStory = buildUnviewStory({ UsersDB, StoriesDB, Id, AppError })
const getStoriesByPublisherId = buildGetStoriesByPublisherId({ UsersDB, StoriesDB, Id, AppError })

module.exports = { addStory, deleteStoryById, getStoryById, likeStory, unlikeStory, getStoriesByPublisherId, viewStory, unviewStory }